const myArray=new Array(0,1,2,3,4,5);
// console.log(myArray);
// myArray.push(6);
// console.log(myArray);
// myArray.pop();
// console.log(myArray);
// myArray.shift();
// console.log(myArray);
// myArray.unshift(1);

// console.log(myArray.includes(15));
// console.log(myArray.indexOf(3));
// const newArray=myArray.join(); 
// console.log(myArray);
// console.log(newArray);
// console.log(typeof myArray);
// console.log(typeof newArray);
console.log("A",myArray);
const m=myArray.slice(0,3);
console.log("Slice",m);
console.log("B",myArray);
const n=myArray.splice(0,3);
console.log("Splice",n);
console.log("C",myArray);